apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftAPIServerConfig
aggregatorConfig:
  clientCA: /etc/kubernetes/ca.crt
  allowedNames:
  - kube-apiserver-proxy
  - system:kube-apiserver-proxy
  - system:openshift-aggregator
  usernameHeaders:
  - X-Remote-User
  groupHeaders:
  - X-Remote-Group
  extraHeaderPrefixes:
  - X-Remote-Extra-
kubeClientConfig:
  kubeConfig: /etc/kubernetes/kubeconfig
servingInfo:
  certFile: /etc/kubernetes/server.crt
  keyFile: /etc/kubernetes/server.key
  clientCA: /etc/kubernetes/ca.crt
storageConfig:
  urls:
    - https://etcd-client:2379
  certFile: /etc/kubernetes/etcd-client.crt
  keyFile: /etc/kubernetes/etcd-client.key
  ca: /etc/kubernetes/ca.crt
apiServerArguments:
  minimal-shutdown-duration:
  - 3s # give SDN some time to converge
