kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-apiserver
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-apiserver
  template:
    metadata:
      labels:
        app: openshift-apiserver
    spec:
      automountServiceAccountToken: false
      containers:
      - name: openshift-apiserver
        image: ${OPENSHIFT_APISERVER_IMAGE}
        args:
        - "start"
        - "--config=/etc/kubernetes/config.yaml"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: openshift-apiserver
        name: secret
