kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-scheduler
  template:
    metadata:
      labels:
        app: kube-scheduler
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-scheduler
        image: registry.svc.ci.openshift.org/origin/4.2-2019-09-16-154910@sha256:218398e93ff8a7c2d638aab4910252f0490d0737344c20253760dba5a7c8e86a
        command:
        - hyperkube
        - kube-scheduler
        args:
        - "--config=/etc/kubernetes/config.yaml"
        - "--cert-dir=/var/run/kubernetes"
        - "--port=0"
        - "--authentication-kubeconfig=/etc/kubernetes/kubeconfig"
        - "--authorization-kubeconfig=/etc/kubernetes/kubeconfig"
        - "-v=2"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: kube-scheduler
        name: secret
