kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-controller-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-controller-manager
  template:
    metadata:
      labels:
        app: kube-controller-manager
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-controller-manager
        image: registry.svc.ci.openshift.org/origin/4.2-2019-09-16-154910@sha256:218398e93ff8a7c2d638aab4910252f0490d0737344c20253760dba5a7c8e86a
        command:
        - hyperkube
        - kube-controller-manager
        args:
        - "--openshift-config=/etc/kubernetes/config.yaml"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: kube-controller-manager
        name: secret
