kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-controller-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-controller-manager
  template:
    metadata:
      labels:
        app: kube-controller-manager
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-controller-manager
        # OCP hyperkube kube-controller-manager still requires --openshift-config
        #image: registry.svc.ci.openshift.org/origin/4.2-2019-09-13-012841@sha256:860cf18486db17475464da470260f8e50d3bd27a327e491c50f7fff866aaf395
        image: k8s.gcr.io/hyperkube:v1.14.6
        command: ["/hyperkube", "kube-controller-manager"]
        args:
        - "--kubeconfig=/etc/kubernetes/kubeconfig"
        - "--root-ca-file=/etc/kubernetes/ca.crt"
        - "--service-account-private-key-file=/etc/kubernetes/service-account"
        - "--service-cluster-ip-range=172.30.0.0/16"
        - "--use-service-account-credentials=true"
        - "--v=2"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: kube-controller-manager
        name: secret
