kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-apiserver
  template:
    metadata:
      labels:
        app: kube-apiserver
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-apiserver
        image: ${HYPERKUBE_IMAGE}
        command:
        - hyperkube
        - kube-apiserver
        args:
        - "--openshift-config=/etc/kubernetes/config.yaml"
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: secret
      volumes:
      - secret:
          secretName: kube-apiserver
        name: secret
