apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-version-operator
spec:
  selector:
    matchLabels:
      k8s-app: cluster-version-operator
  strategy:
    type: Recreate
  template:
    metadata:
      name: cluster-version-operator
      labels:
        k8s-app: cluster-version-operator
    spec:
      containers:
      - name: cluster-version-operator
        image: quay.io/csrwng/release:hosted
        imagePullPolicy: IfNotPresent
        args:
          - "start"
          - "--release-image=quay.io/csrwng/release:hosted"
          - "--enable-auto-update=false"
          - "--enable-default-cluster-version=true"
          - "--kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig"
          - "--v=4"
          - "--exclude-manifests=.*_kube-apiserver-operator_.*"
          - "--exclude-manifests=.*_kube-controller-manager-operator_.*"
          - "--exclude-manifests=.*_kube-scheduler-operator_.*"
          - "--exclude-manifests=.*_machine-api-operator_.*"
          - "--exclude-manifests=.*_openshift-apiserver-operator_.*"
          - "--exclude-manifests=.*_cloud-credential-operator_.*"
          - "--exclude-manifests=.*_cloud-credential-operator_.*"
          - "--exclude-manifests=.*_cluster-autoscaler-operator_.*"
          - "--exclude-manifests=.*_cluster-machine-approver_.*"
          - "--exclude-manifests=.*_openshift-controller-manager-operator_.*"
          - "--exclude-manifests=.*_openshift-controller-manager-operator_.*"
          - "--exclude-manifests=.*_cluster_monitoring_operator_.*"
          - "--exclude-manifests=.*_insights-operator_.*"
          - "--exclude-manifests=.*_machine-config-operator_.*"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - mountPath: /etc/cvo/updatepayloads
            name: etc-cvo-updatepayloads
            readOnly: true
          - mountPath: /etc/kubernetes/kubeconfig
            name: kubeconfig
            readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
        - name: etc-cvo-updatepayloads
          emptyDir: {}
        - name: kubeconfig
          secret:
            secretName: cluster-version-operator
