kind: Deployment
apiVersion: apps/v1
metadata:
  name: openvpn-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openvpn-server
  template:
    metadata:
      labels:
        app: openvpn-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: openvpn-server
        image: quay.io/sjenning/poc:openvpn
        imagePullPolicy: Always
        command:
        - /usr/sbin/openvpn
        - --config
        - /etc/openvpn/server.conf
        workingDir: /etc/openvpn/
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/openvpn/
          name: secret
      volumes:
      - secret:
          secretName: openvpn-server
        name: secret
